### ISSUE TITLE
Check time

### ISSUE THREAD

**Issue by jmcolmenar** [GRAFO-URJC/WebGE#112]
The hour of experiments is 2 hours earlier. Check time zone.

**Comment by leichenxu** [comment]
@jmcolmenar check if the commit solve the problem

**Comment by jmcolmenar** [comment]
Exception launched in "My experiments":
An error happened during template parsing (template: "class path resource [templates/experiment/experimentRepository.html]")

**Comment by leichenxu** [comment]
> Exception launched in "My experiments":
> An error happened during template parsing (template: "class path resource [templates/experiment/experimentRepository.html]")

need more details, this is a thymeleaf rendering something null error

**Comment by jmcolmenar** [comment]
Still the same error:

Caused by: org.attoparser.ParseException: Exception evaluating SpringEL expression: "exp.getIdRunList().isEmpty()?
                                             exp:exp.getIdRunList().get(exp.getIdRunList().size()-1)" (template: "experiment/experimentRepository" - line 89, col 45)
	at org.attoparser.MarkupParser.parseDocument(MarkupParser.java:393)
	at org.attoparser.MarkupParser.parse(MarkupParser.java:257)
	at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:230)
	... 87 more
Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "exp.getIdRunList().isEmpty()?
                                             exp:exp.getIdRunList().get(exp.getIdRunList().size()-1)" (template: "experiment/experimentRepository" - line 89, col 45)

**Comment by leichenxu** [comment]
@jmcolmenar in the new commit removing the variable should be solve the problem, check it

**Comment by jmcolmenar** [comment]
Corrected
